### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by caijiaping** [minhup/Energy-Disaggregation#1]
I have requested the dataset download access. Unfortunately, I haven't received the feedback yet.
Currently, I am working on an electricity disaggregation project. I really want to try your codes. Is it possible that you can share the dataset with me?

Thanks

**Comment by minhup** [comment]
Hi,

Unfortunately, I no longer have the data. I lost the data when changing my
computer.

Regards

**Comment by MarianaOliveira94** [comment]
Hi, I have the same problem, have you already receive the access?

**Comment by caijiaping** [comment]
No, I haven't received any reply. I don't know if they stopped maintenance the dataset.

**Comment by joaqrus** [comment]
It is working again. It is possible to download the data with the provided user/password.

**Comment by Mastersam07** [comment]
I was able to download the dataset. Just use the user/password provided in the project README
